#5 - User session, recovery & errors handler
proyecto-arima/backend pull request #12
Opened 2024-07-26 19:35 UTC by Matiassgg

@aleeherasimiuk Agregue un par de cambios core a los errores que lanzamos desde el service de auth como te comente estos dias

- Agregue unos cambios al logger y al smtp, quedara pendiente el test del envio de mails en esta PR
- El logueo y deslogueo ya estan, con sus tests ok

2024-07-27 18:22 UTC, aleeherasimiuk requested changes

2024-07-27 18:22 UTC, aleeherasimiuk commented on src/api/auth/authService.ts
> +      }
Todo esto no es necesario, loggear donde se dispara el primer error y luego enviar el error al errorHandler con next.

2024-07-27 18:22 UTC, aleeherasimiuk commented on src/api/auth/authService.ts
> +      );
Todo esto ya tendríamos que poder llevarlo a un .html

2024-07-27 18:22 UTC, aleeherasimiuk commented on src/api/user/userRepository.ts
> +      return Promise.reject();
Está bien usar UserNotFoundError, te va a permitir mejorar el handling de errores.

2024-07-27 18:22 UTC, aleeherasimiuk commented on src/api/user/userService.ts
>      }
A esta altura el repo ya tendría que haber lanzado un error, !user no tendría que ser nunca verdadero...

2024-07-28 18:20 UTC, Matiassgg commented on src/api/auth/authService.ts
> +      );
Ya hay un `template_welcome_mail.html` pero no lo estamos usando todavia. Hay que agregar la tarea en algun sprint

2024-07-28 18:32 UTC, Matiassgg commented on src/api/user/userService.ts
>      }
Me lo marcaba el IDE esto como que podia ser null, asi que porlas lo agregue, solo eso

2024-07-28 20:43 UTC, Matiassgg commented
@aleeherasimiuk Me parece que no se esta probando del todo bien el SMTP en el pipeline, comente el envio del mail de recovery y anduvo el CI. Lo anoto para verlo.

Creo que tiene que ver con el mock

2024-07-30 22:18 UTC, aleeherasimiuk approved these changes

2024-07-30 22:18 UTC, merged